# Generated by Django 2.0 on 2018-02-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0006_auto_20180206_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreitada',
            name='sub_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_emp', to='projeto_p3.sub_empreiteiros'),
            preserve_default=False,
        ),
    ]
