# Generated by Django 2.0 on 2018-02-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0010_auto_20180207_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empreiteiros',
            old_name='parent_example',
            new_name='subempreiteiro',
        ),
    ]
