# Generated by Django 2.0.2 on 2018-03-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0022_relatorio_mensal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='relatorio_mensal',
            new_name='relatorios_mensais',
        ),
    ]
