# Generated by Django 2.0.2 on 2018-03-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0025_auto_20180306_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreiteiros',
            name='subempreiteiro',
            field=models.ManyToManyField(blank=True, related_name='_empreiteiros_subempreiteiro_+', to='projeto_p3.empreiteiros'),
        ),
    ]
