# Generated by Django 2.0 on 2018-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(upload_to='img'),
        ),
    ]
