# Generated by Django 2.0 on 2018-02-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0004_auto_20180119_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='empreitada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='empreiteiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=500)),
                ('morada', models.CharField(max_length=500)),
                ('atividade', models.CharField(max_length=500)),
                ('alvara', models.CharField(max_length=500)),
                ('nif', models.CharField(max_length=500)),
                ('nome_representante', models.CharField(max_length=500)),
                ('contacto_representante', models.CharField(max_length=500)),
                ('num_ap_seguro_resp_civil', models.CharField(max_length=500)),
                ('data_seguro_resp_civil', models.DateField()),
                ('validade_seguro_resp_civil', models.CharField(max_length=500)),
                ('data_decl_ss', models.DateField()),
                ('validade_decl_ss', models.CharField(max_length=500)),
                ('data_cert_financas', models.DateField()),
                ('validade_cert_financas', models.CharField(max_length=500)),
                ('mes_folha_ferias', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=500)),
                ('recibo_folha_ferias', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=500)),
                ('horario_trabalho', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=500)),
                ('declaracao_pss', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=500)),
                ('declaracao_imigrantes', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=500)),
                ('contrato_subempreitada', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=500)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras1', to='projeto_p3.obras')),
            ],
        ),
        migrations.CreateModel(
            name='trabalhadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('num_di', models.CharField(max_length=500)),
                ('validade_di', models.DateField()),
                ('dn', models.CharField(max_length=500)),
                ('nif', models.CharField(max_length=500)),
                ('niss', models.CharField(max_length=500)),
                ('resultado_insp_med', models.CharField(choices=[('Apto', 'Apto'), ('Não', 'Não')], max_length=500)),
                ('data_insp_med', models.DateField()),
                ('validade_insp_med', models.CharField(max_length=500)),
                ('registo_epis', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não aplicavél', 'Não aplicavél')], max_length=500)),
                ('registo_formacao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não aplicavél', 'Não aplicavél')], max_length=500)),
                ('cp', models.CharField(max_length=500)),
                ('contrato_act', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não aplicavél', 'Não aplicavél')], max_length=500)),
                ('seguro_at', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não aplicavél', 'Não aplicavél')], max_length=500)),
                ('declaracao_manobrador', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não aplicavél', 'Não aplicavél')], max_length=500)),
                ('carta_riscos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não aplicavél', 'Não aplicavél')], max_length=500)),
                ('idade', models.CharField(max_length=500)),
                ('data_entrada_obra', models.DateField()),
                ('data_saida_obra', models.DateField()),
                ('empreiteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trab', to='projeto_p3.empreiteiros')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='cartao_combustivel',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='outros',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='portatil',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='utilizador',
        ),
        migrations.AddField(
            model_name='empreitada',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='projeto_p3.empreiteiros'),
        ),
        migrations.AddField(
            model_name='empreitada',
            name='equipamentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='projeto_p3.equipamentos'),
        ),
        migrations.AddField(
            model_name='empreitada',
            name='trabalhadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trab1', to='projeto_p3.trabalhadores'),
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='empreiteiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emp1', to='projeto_p3.empreiteiros'),
            preserve_default=False,
        ),
    ]
