# Generated by Django 2.0 on 2018-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0007_empreitada_sub_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreiteiros',
            name='apolice_seguro_trabalho',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreiteiros',
            name='companhia_seguro_trabalho',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreiteiros',
            name='modalidade_seguro_trabalho',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreiteiros',
            name='valdade_seguro_trabalho',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
