# Generated by Django 2.0 on 2018-02-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0008_auto_20180207_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreiteiros',
            name='parent_example',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cenas222', to='projeto_p3.empreiteiros'),
            preserve_default=False,
        ),
    ]
