# Generated by Django 2.0 on 2018-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0011_auto_20180207_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='subempreiteiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_geral', models.ManyToManyField(to='projeto_p3.empreiteiros')),
            ],
        ),
    ]
