# Generated by Django 2.0 on 2018-02-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0012_subempreiteiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='subempreiteiros',
            name='sub_emp_geral',
            field=models.ManyToManyField(to='projeto_p3.empreiteiros'),
        ),
        migrations.RemoveField(
            model_name='subempreiteiros',
            name='emp_geral',
        ),
        migrations.AddField(
            model_name='subempreiteiros',
            name='emp_geral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trabas', to='projeto_p3.empreiteiros'),
            preserve_default=False,
        ),
    ]
