# Generated by Django 2.0 on 2018-02-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0013_auto_20180214_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subempreiteiros',
            old_name='sub_emp_geral',
            new_name='subempreiteiro',
        ),
    ]
