# Generated by Django 2.0 on 2018-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_p3', '0014_auto_20180214_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreiteiros',
            name='subempreiteiro',
        ),
        migrations.AddField(
            model_name='empreiteiros',
            name='subempreiteiro',
            field=models.ManyToManyField(related_name='_empreiteiros_subempreiteiro_+', to='projeto_p3.empreiteiros'),
        ),
    ]
